use_frameworks!

platform :ios, '12.0'

target 'EZGraphQL_Example' do
  pod 'EZGraphQL', :path => '../'
  pod "Apollo", '~> 0.19.0'
  target 'EZGraphQL_Tests' do
    inherit! :search_paths

    
  end
end
